config/routes.rb
Rails.application.routes.draw do
  resources :cost_centers
  resources :rafs
  resources :enrollments
  resources :training_categories
  resources :training_programs
  resources :gradings
  resources :grades do
    member do
      put 'up'
      put 'down'
    end
  end
  resources :groups do
    member do
      put 'up'
      put 'down'
    end
  end
  resources :job_statuses do
    member do
      put 'remove_person'
    end
  end
  resources :people
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  patch 'date', to: 'date#update'

  root to: 'groups#index'
end

app/models/grade.rb
class Grade < ApplicationRecord
  SUPER_GRADES = ['Haken', 'Contract', 'S', 'C', 'E', 'J'].freeze
  acts_as_list
  has_many  :gradings, dependent: :restrict_with_error
  has_many  :people, through: :gradings, dependent: :restrict_with_error

  validates :name, presence: true
  validates :super_grade, presence: true
  validates :super_grade, inclusion: {in: SUPER_GRADES, message: "%<value>s は許可されていない値です"}

  # Counts the super_grades for all people belonging to specified groups
  # at the specified date.
  # Returns something like {'Haken' => 2, 'S' => 5, 'E' => 1, 'J' => 1}
  def self.head_count_grouped_by_grades_for_groups_at_date(groups, date)
    all_job_statuses = JobStatus.at(date)
                                .where(group_id: groups.collect(&:id))
    grouped_grades = Grading.at(date).joins(:grade)
                            .where(person_id: all_job_statuses.real.collect(&:person_id))
                            .group(:super_grade).count
    Grade::SUPER_GRADES.each { |super_grade| grouped_grades[super_grade] ||= 0 }
    grouped_grades['not-Graded'] = all_job_statuses.real.left_outer_joins(person: :gradings)
                                  .where("gradings.id IS NULL").count
    grouped_grades['Open'] = all_job_statuses.placeholders.count
    grouped_grades
  end

end

app/controllers/grades_controller.rb
# frozen_string_literal: true

class GradesController < ApplicationController
  before_action :set_grade, only: [:show, :edit, :update, :destroy, :up, :down]

  # GET /grades
  # GET /grades.json
  def index
    @grades = Grade.all.order(:position)
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to @grade, notice: 'Grade was successfully created.' }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to @grade, notice: 'Grade was successfully updated.' }
        format.js   { redirect_to @grade, notice: 'Grade was successfully updated.' }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit }
        format.js   { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # PUT /grades/1/up
  def up
    @grade.move_higher
    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Grade was moved up.' }
      format.json { head :no_content }
    end
  end

  # PUT /grades/1/down
  def down
    @grade.move_lower
    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Grade was moved down.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_grade
    @grade = Grade.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def grade_params
    params.require(:grade).permit(:name, :position, :super_grade, :notes)
  end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/_form.html.erb
<%= bs_details_modal do %>
  <%= form_with(model: grade) do |form| %>
    <%= bs_modal_header title: "Edit Grade" %>
    <div class="modal-body" id="details-modal-body">
      <%= error_messages_box grade %>

      <div class="row">
        <div class="col">
          <%= bs_text_field form, :name %>
        </div>
        <div class="col">
          <%= bs_text_field form, :super_grade %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= bs_text_area form, :notes %>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <% if grade.persisted? %>
        <%= link_to 'Destroy', grade, method: :delete, data: { confirm: 'DESTROY GRADE: Are you sure?' }, class: "btn btn-danger mr-5" %>
      <% end %>
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      <%= form.submit class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/grades/_profile.html.erb
<p id="notice"><%= notice %></p>

<% content_for :controls do %>
  <%= link_to 'Edit', edit_grade_path(grade), remote: true, data: {toggle: "modal", target: "#detailsModal"}, class: "btn btn-primary" %>
<% end %>

<h3><%= grade.name %></h3>

<%= bs_attribute "SuperGrade", grade.super_grade %>

<div>
  <strong>Notes:</strong>(<%= markdown_syntax_link %>)
  <%= markdown_render grade.notes %>
</div>

app/views/grades/edit.html.erb
<h1>Editing Grade</h1>

<%= render 'form', grade: @grade %>

<%= link_to 'Show', @grade %> |

app/views/grades/edit.js.erb
<%= js_insert_content_into_id id: 'detailsModal',
                         content: (render partial: 'form', locals: {grade: @grade}),
                         textareas_to_adjust: ['grade_notes'] %>

app/views/grades/index.html.erb
<p id="notice"><%= notice %></p>

<% content_for :controls do %>
  <%= render :partial => "date/button" %>
  <%= link_to 'New Grade', new_grade_path, remote:true, data: {toggle: "modal", target: "#detailsModal"}, class: "btn btn-primary" %>
<% end %>

<h1 class="clearfix">Grades</h1>

<table class="table table-sm">
  <thead class="thead-light">
    <th scope="col">Name</th>
    <th scope="col">Count</th>
    <th scope="col">SuperGrade</th>
    <th scope="col"></th>
  </thead>

  <tbody>
    <% @grades.each do |grade| %>
      <tr>
        <td><%= link_to grade.name, grade %></td>
        <td><%= grade.gradings.at(display_for_date).count %></td>
        <td><%= grade.super_grade %></td>
        <td><%= link_to 'Up', up_grade_path(grade), :method => :put %> <%= link_to 'Down', down_grade_path(grade), :method => :put %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/grades/new.html.erb
<h1>New Grade</h1>

<%= render 'form', grade: @grade %>

<%= link_to 'Back', grades_path %>

app/views/grades/new.js.erb
<%= js_insert_content_into_id id: 'detailsModal',
                         content: (render partial: 'form', locals: {grade: @grade}),
                         textareas_to_adjust: ['grade_notes'] %>

app/views/grades/show.html.erb
<div id="object-content">
  <%= render "profile", grade: @grade %>
</div>

<h3>Current Gradings</h3>
<table class="table table-sm">
  <thead class="thead-light">
    <%= render partial: 'gradings/grading_header' %>
  </thead>
  <tbody>
    <%= render partial: 'gradings/grading', collection: @grade.gradings.current.joins(:person).order(:birth_date) %>
  </tbody>
</table>

app/views/grades/show.js.erb
var grade_profile = document.getElementById('grade_profile');
grade_profile.innerHTML = "<%= j render 'profile', grade: @grade %>"