config/routes.rb
Rails.application.routes.draw do
  resources :cost_centers
  resources :rafs
  resources :enrollments
  resources :training_categories
  resources :training_programs
  resources :gradings
  resources :grades do
    member do
      put 'up'
      put 'down'
    end
  end
  resources :groups do
    member do
      put 'up'
      put 'down'
    end
  end
  resources :job_statuses do
    member do
      put 'remove_person'
    end
  end
  resources :people
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  patch 'date', to: 'date#update'

  root to: 'groups#index'
end

app/models/person.rb
# frozen_string_literal: true

# Person lifecycle
#
# We don't want orphaned Person objects lying around so we need to clearly define how People are created and
# how they can be destroyed.
#
# Since we don't want orphan People lying around, a Person must always be associated with a JobStatus.
# Therefore, we won't create a Person independently, but instead always create a JobStatus and then
# create a Person. A Person always needs to have an assoicated job_status.
class Person < ApplicationRecord
  include DatesCommon

  ACADEMIC = ['High School', 'College', 'Bachelor', 'Master', 'Doctor'].freeze
  # JobStatus dependency is set to :nullify. However,
  # we will separately verify in a before_destroy callback
  # that there are no JobStatus objects with placeholder: false.
  # To ensure this before_destroy is called before :nullify, place it
  # before `has_many  :job_statuses, dependent: :nullify`, since
  # dependent: :nullify also registers into the before_destroy callback
  # chain.
  before_destroy :ensure_absence_of_non_placeholder_job_statuses

  # ActiveStorage
  # Read https://evilmartians.com/chronicles/rails-5-2-active-storage-and-beyond
  # for more information on ActiveStorage
  has_one_attached :avatar
  has_many_attached :attachments

  has_many  :job_statuses, dependent: :nullify
  has_many  :gradings, dependent: :restrict_with_error
  has_many  :enrollments, dependent: :restrict_with_error
  delegate :job_title_jp, :job_title_en, :group, :group_leader, to: :current_status, allow_nil: true
  delegate :grade, to: :current_grading, allow_nil: true
  validates :name_jp, presence: true
  validates :name_en, format: { with: /\A\w+,\s\w+\z/, message: ' is not valid En name. Use [Family name], [Given name] format.', allow_blank: true }
  validates :job_statuses, presence: true
  validates :email, format: { with: /\A[\w\-.]+@agc(bio)?\.com/, message: 'is not a valid AGC/AGC Bio email address' },
                    allow_blank: true

  # Currently hired employees
  scope :hired, lambda {
    joins(:job_statuses)
      .where("job_statuses.started_at < ? AND ? < job_statuses.ended_at", Time.zone.today, Time.zone.today)
      .where("job_statuses.placeholder" => false)
      .where("job_statuses.group_id" => Group.hired_groups.map(&:id))
  }

  # Current People as placeholders for open positions
  scope :open, lambda {
    joins(:job_statuses)
      .where("job_statuses.started_at < ? AND ? < job_statuses.ended_at",
             Time.zone.today,
             Time.zone.today)
      .where("job_statuses.placeholder" => true)
  }

  # Current orphaned People (with no associated current_status)
  scope :orphaned, lambda {
    joins('LEFT OUTER JOIN job_statuses ON job_statuses.person_id = people.id').where('job_statuses.id IS NULL')
  }
  # Has Master's degree
  scope :master_deg, -> { where(academic_id: Person::ACADEMIC.find_index('Master')) }
  # Haken
  scope :haken, -> { where(id: Grading.haken.current.collect(&:person_id)) }

  def academic
    ACADEMIC[academic_id] if academic_id.present?
  end

  def age(date = Time.zone.today)
    years_since(birth_date, date)
  end

  def years_since_joined
    years_since(joined_date)
  end

  def joined_at_age
    years_since(birth_date, joined_date)
  end

  def current_status
    @current_status ||= job_statuses.current.first
  end

  def current_grading
    @current_grading ||= gradings.current.first
  end

  def joined?
    job_statuses.current.real.any?
  end

  def hired
    current_status && !current_status.placeholder ? true : false
  end

  def grade_at(date)
    grading = gradings.at(date).first
    grading ? grading.grade : nil
  end

  def haken_at?(date)
    grade = grade_at(date)
    grade && (grade.name == 'Haken') ? true : false
  end

  # Clean up name
  def name_jp=(string)
    string.sub!(/(?u)\s/, ' ') # (?u) turns on Unicode matching
    self[:name_jp] = string
  end

  def given_name_en
    splitted_name_en.first
  end

  def family_name_en
    splitted_name_en.last
  end

  def splitted_name_en
    return [] if name_en.blank?
    @splitted_name_en ||= name_en.split(%r{(?u),\s*})
  end

  # Get an array of managers in which this Person reports to.
  # Each Group returns leaders as an Array of People since
  # there can be multiple Group leaders in the current implementation
  def reporting_line
    @reporting_line ||= group.self_and_ancestors.reverse.map do |g|
      gl = g.current_leaders
      gl.empty? ? nil : gl
    end.compact!
  end

  def direct_report
    reporting_line.first
  end

  # This is for generating a CSV based report
  # where the reporting line should be padded
  # with the highest in hierarchy at the end
  # and empty ranks as nil.
  # The number of elements is defined as array_size
  def reporting_line_padded(array_size = 6)
    (Array.new(array_size, []) + reporting_line)[-array_size..-1]
  end

  # Use the uploaded new_attachment params to
  # add attachments to what we already have
  def new_attachments=(params)
    attachments.attach(params)
  end

  # Acts on a scope
  def self.to_csv
    CSV.generate(headers: true) do |csv|
      all.each do |p|
        row = []
        row << p.given_name_en
        row << p.family_name_en
        row << p.name_jp
        row << p.email
        row << p.birth_date
        row << "CHB"
        row << p.joined_date
        row << (p.haken_at?(Time.zone.today) ? "Haken" : "FTE")
        row << ""
        row << ""
        row << ""
        row << p.years_since_joined
        row << p.group.name_jp
        row << p.reporting_line.first&.first&.given_name_en
        row << p.reporting_line.first&.first&.family_name_en
        p.reporting_line_padded(6).each do |r|
          if r.first.nil?
            row << ""
            row << ""
          else
            row << r.first.name_en
            row << r.first.group.name_jp
          end
        end
        csv << row
      end
    end
  end

  # obfuscators for demo
  def name_jp
    "山田 太郎"
  end

  def name_en
    "Jon Doe"
  end

  def notes
    "何かメモ"
  end

  def email
    "some-email@somedomain.com"
  end

  def employee_number
    123456
  end

  def birth_date
    Date.new(1980,1,1)
  end

  def joined_date
    Date.new(2010,2,1)
  end

  private

  def ensure_absence_of_non_placeholder_job_statuses
    return if job_statuses.real.empty?

    errors.add :job_statuses, 'which are not placeholders remain.'
    throw :abort
  end
end

app/controllers/people_controller.rb
# frozen_string_literal: true
require 'csv'

class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :set_job_status, only: [:new, :create]

  # GET /people
  # GET /people.json
  # rubocop:disable Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
  def index
    @people = Person.all

    if params[:filter]
      @people = @people.haken if params[:filter].include?("haken")
      @people = @people.master_deg if params[:filter].include?("master")
      @people = @people.hired if params[:filter].include?("hired")
    end

    if params[:order]
      @people = @people.order('people.birth_date' => :desc) if params[:order] == "age_asc"
      @people = @people.order('people.birth_date' => :asc) if params[:order] == "age_desc"
    else
      @people = @people.order('people.birth_date' => :desc)
    end

    respond_to do |format|
      format.html { render :index }
      format.csv { send_data @people.to_csv, filename: "people-#{Time.zone.today}.csv" }
    end
  end
  # rubocop:enable Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people?job_status_id=1
  # POST /people.json
  def create
    @person = Person.new(person_params)
    @person.job_statuses << @job_status

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.js { redirect_to @person, notice: 'Person was successfully created.' }
        # format.js   { render :show, locals: {notice: 'Person was successfully created.'}}
      else
        format.html { render :new }
        format.js   { render :new }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.js   { redirect_to @person, notice: 'Person was successfully updated.' }
      else
        format.html { render :edit }
        format.js   { render :edit }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    respond_to do |format|
      if @person.destroy
        flash.notice = 'Person was successfully destroyed.'
        format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
        format.js { render inline: "location.href = document.referrer", notice: 'Person was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.js   { render :edit }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
  end

  def set_job_status
    @job_status = JobStatus.find(params[:job_status_id])
  end

  # Only allow a list of trusted parameters through.
  def person_params
    params.require(:person).permit(:employee_number, :name_jp, :name_en, :email,
                                   :birth_date, :joined_date, :avatar,
                                   :notes, :address, :hometown, :education, :raf, :academic_id,
                                   new_attachments: [])
  end
end

app/helpers/people_helper.rb
module PeopleHelper
  def css_class_for(person)
    if person.hired
      ""
    else
      "open"
    end
  end

  def image_tag_for_no_photo(args = {})
    image_tag("faces/no-photo.png", args)
  end

  def image_tag_for_person(person, args = {})
    # if person.avatar.attached?
    if false
      url = url_for(person.avatar)
      link_to image_tag(url, args), url
    else
      image_tag_for_no_photo(args)
    end
  end

  # filter_link "派遣", :haken
  def filter_link_to(title, filter_tag)
    params_array = params[:filter].to_a
    filter_tag_as_string = filter_tag.to_s
    if params_array.include?(filter_tag_as_string)
      new_params_array = params_array.uniq - [filter_tag_as_string]
      css_class = "btn btn-primary"
    else
      new_params_array = (params_array + [filter_tag_as_string]).uniq
      css_class = "btn btn-outline-primary"
    end
    link_to title, people_path(modified_params_hash(filter: new_params_array)), class: css_class
  end

  def order_link_to(title, order_tag)
    order_tag_as_string = order_tag.to_s
    css_class = if params[:order] == order_tag_as_string
                  "btn btn-primary"
                else
                  "btn btn-outline-primary"
                end
    link_to title,
            people_path(modified_params_hash(order: order_tag_as_string)),
            class: css_class
  end

  def time_since_joined_in_words(person)
    if person.joined_date && (person.joined_date <= Time.zone.today)
      distance_of_time_in_words_to_now person.joined_date
    else
      ""
    end
  end
end

app/views/people/_associations.html.erb
<h3>Assignments<div class="float-right"><%= link_to "New Assignment", new_job_status_path(job_status: {person_id: person}), remote: true, data: {toggle:"modal", target:"#detailsModal"}, class: "btn btn-primary btn-sm" %></div></h3>

<div class="table-responsive">
  <table class="table table-sm">
    <thead class="thead-light">
      <tr>
        <th scope="col">Term</th>
        <th scope="col">Person</th>
        <th scope="col">Assigned to Group</th>
        <th scope="col">Title</th>
        <th scope="col">Reports to</th>
      </tr>
    </thead>

    <tbody>
  	<%= render partial: "job_statuses/job_status", collection: person.job_statuses.order(started_at: :desc) %>
    </tbody>
  </table>
</div>

<h3>Gradings<div class="float-right"><%= link_to "New Grading", new_grading_path(grading: {person_id: person}), remote: true, data: {toggle:"modal", target:"#detailsModal"}, class: "btn btn-primary btn-sm" %></h3>

<div class="table-responsive">
  <table class="table table-sm">
    <thead class="thead-light">
      <%= render partial: 'gradings/grading_header' %>
    </thead>

    <tbody>
      <%= render partial: "gradings/grading", collection: person.gradings.order(started_at: :desc) %>
    </tbody>
  </table>
</div>

<div class="controls">

</div>

<h3>Trainings<div class="float-right"><%= link_to "New Training", new_enrollment_path(enrollment: {person_id: @person}), class: "btn btn-primary btn-sm" %></div></h3>
<%= render partial: "enrollments/enrollments_table", locals: {enrollments: person.enrollments} %>

app/views/people/_form.html.erb
<%= bs_details_modal size: "none" do %>
  <%= form_with(model: person) do |form| %>
    <%= bs_modal_header title: "Edit Person" + (" for #{link_to person.name_jp, person}").to_s %>
    <div class="modal-body" id="details-modal-body">
      <%= error_messages_box person %>
      <%= hidden_field_tag :job_status_id, @job_status.id unless person.persisted? %>
      <!-- Photo and name row -->
      <div class="row align-items-center form-group">
        <div class="image-cell col-sm-4">
          <%= image_tag_for_person(person, style: "max-width: 200px;max-height:200px") %>
          <div class="field">
            <%= form.file_field :avatar %>
          </div>
        </div>
        <div class="col-sm-8">
          <%= bs_text_field form, :name_jp, "名前 (日本語)" %>
          <%= bs_text_field form, :name_en, "名前 (英語: [姓], [名])" %>
        </div>
      </div>
      <!-- Other Person information -->
      <div>
        <div class="row">
          <div class="col">
            <%= bs_text_field form, :employee_number %>
          </div>
          <div class="col">
            <%= bs_text_field form, :email %>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <%= bs_text_field form, :birth_date %>
          </div>
          <div class="col">
            <%= bs_text_field form, :joined_date, "Joined (AGC)" %>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <%= bs_select form, :academic_id, "Academic", Person::ACADEMIC.map.with_index{|a,id| [a,id]}, {include_blank: true}, {class: "form-control"} %>
          </div>
          <div class="col">
            <%= bs_text_area form, :education %>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <%= bs_text_field form, :hometown %>
          </div>
          <div class="col">
            <%= bs_text_area form, :address %>
          </div>
        </div>
        <%= bs_text_area form, :notes %>
        <div class="form-group">
          <%= form.label :new_attachments %>
          Add attachments
          <%= form.file_field :new_attachments, {multiple: true, class: "form-control"} %>
          <% unless person.attachments.attached? %>
            No attachments yet.
          <% else %>
            <ul>
              <% person.attachments.attachments.each do |a| %>
                <li><%= link_to a.filename.to_s, url_for(a) %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <% if person.persisted? %>
        <%= link_to 'destroy person', person, method: :delete, data: { confirm: 'DESTROY PERSON: Are you sure?' }, remote: true, class: "btn btn-danger mr-5" %>
      <% end %>
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/people/_person.html.erb
<div class="<%= css_class_for person %>" data-controller="person">
  <div class="row align-items-center">
    <div class="image-cell col-sm-auto p-3">
      <%= image_tag_for_person(person, style: "max-width: 200px;max-height:200px") %>
    </div>
    <div class="col <%= person.hired ? '' : 'open'%> center">
      <div class="float-right"><%= link_to 'Edit', edit_person_path(person), remote: true, id: "edit_person_link", data: {toggle:"modal", target:"#detailsModal"}, class: "btn btn-primary" %></div>
      <h3>
        <%= person.name_jp %> <%= person.name_en %>
      </h3>
      <h4>
        <%= link_to person.group.name_jp, person.group if person.group %>
        <%= person.job_title_jp if person.job_title_jp %>
        <%= person.group_leader ? "Group Leader" : "" %>
      </h4>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= bs_attribute "Employee #" do %>
        <%= person.haken_at?(Time.zone.today) ? "派遣" : "" %>
        <%= person.employee_number %>
      <% end %>
    </div>
    <div class="col">
      <%= bs_attribute "e-mail", person.email %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= bs_attribute "Birth date", person.birth_date %>
    </div>
    <div class="col">
      <%= bs_attribute "Age", person.age %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= bs_attribute "Joined AGC" do %>
        <% if person.joined_date %>
          <%= person.joined_date %> @age <%= person.joined_at_age %>
        <% end %>
      <% end %>
    </div>
    <div class="col">
      <%= bs_attribute "Time in AGC", time_since_joined_in_words(person) %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= bs_attribute "Degree", person.academic %>
    </div>
    <div class="col">
      <%= bs_attribute "Education", markdown_render(person.education) %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= bs_attribute "Address", markdown_render(person.address) %>
    </div>
    <div class="col">
      <%= bs_attribute "Hometown", person.hometown %>
    </div>
  </div>
  <div id="person_notes">
    <strong>Notes:</strong>(<%= markdown_syntax_link %>)
    <div>
      <% if person.notes.blank? %>
        No notes yet.
      <% else %>
        <div class="text-left">
          <a href="#" data-action="click->person#toggleNotes" data-target="person.toggleNotesButton">Notes are Hidden: Show notes?</a>
        </div>
        <div id="notes" data-target="person.notesText" style="display:none">
          <%= markdown_render person.notes %>
        </div>
      <% end %>
    </div>
  </div>
  <div id="person_attachments">
    <strong>Attachments:</strong>(<%= markdown_syntax_link %>)
    <div>
      <% unless person.attachments.attached? %>
        No attachments yet.
      <% else %>
        <ul>
          <% person.attachments.attachments.each do |a| %>
            <li><%= link_to a.filename.to_s, url_for(a) %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/people/_person_as_row.html.erb
<tr class="<%= person.hired ? '' : 'open' %>">
  <td style="height:70px;width:57px;padding:2px">
    <%= image_tag_for_person(person, style: "height:70px") %>
  </td>
  </td>
  <td>
    <%= link_to person.name_jp, person %> <%= person.name_en %><br>
    Email: <%= person.email %><br>
    Grade: <%= person.current_grading ? link_to(person.current_grading.grade.name, grade_path(person.current_grading.grade)) : "No Grading" %><br>
    Education: <%= "#{person.academic} from #{person.education}" %><br>
    Age: <%= person.age %>
  </td>
  <td>
    <p>
      <%= !person.group.blank? ? link_to(person.group.name_jp, group_path(person.group)) : "No Role" %>
      <%= person.job_title_jp %>
    </p>
    <p>
      Joined AGC: <%= person.haken_at?(Time.zone.today) ? "派遣 " : "" %><%= distance_of_time_in_words_to_now(person.joined_date) if person.joined_date %> ago</p>
    </p>
  </td>
</tr>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<div id="person">
	<%= render 'form', person: @person %>
</div>

<div class="controls">
	<%= link_to 'Show', @person %> |
	<%= link_to 'Destroy', @person, method: :delete, data: { confirm: 'DESTROY PERSON: Are you sure?' } %>
</div>

<%= render "associations", person: @person %>

app/views/people/edit.js.erb
<%= js_insert_content_into_id id: 'detailsModal',
                         content: (render partial: 'form', locals: {person: @person}),
                         textareas_to_adjust: ['person_notes'] %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<% bs_help_modal "People Help" do %>
  <dl>
    <dt>新しいPersonを追加</dt>
    <dd>
      Personを追加するのはここではできない。Assignmentを先に作って、そこから新規にPersonを作る。
      PersonはAssignmentなしに作ることはできないため。
    </dd>
  </dl>
<% end %>


<h1>People</h1>
<div class="row mb-2">
  <div class="col">
    <fieldset class="border border-primary p-1">
    	<legend class="text-center">Filter (<%= @people.size %> people)</legend>
    	<%= link_to '解除', people_path, class: "btn btn-outline-primary" %>
    	<%= filter_link_to '雇用中', :hired %>
    	<%= filter_link_to '派遣', :haken %>
    	<%= filter_link_to '修士卒', :master %>
    </fieldset>
  </div>
  <div class="col">
    <fieldset class="border border-primary p-1">
    	<legend class="text-center">Order</legend>
    	<%= order_link_to '年齢昇順', :age_asc %>
    	<%= order_link_to '年齢降順', :age_desc %>
    </fieldset>
  </div>
</div>
<% if !params[:filter] && !Person.orphaned.empty? %>
	<h2>Orphaned without assignments - Need to fix by giving them assignments or deleting</h2>
	<table class="table table-sm">
    <thead class="thead-light">
      <th scope="col" class="w-auto">Photo</th>
      <th scope="col" class="w-50">Person</th>
      <th scope="col" class="w-auto">Assignments</th>
    </thead>
	  <tbody>
	    <% Person.orphaned.each do |person| %>
	      <%= render partial: "person_as_row", locals:{person: person} %>
	    <% end %>
	  </tbody>
	</table>
	<br>
<% end %>
<div class="text-right">
  <%= link_to "Export as CSV", people_path(format: "csv", filter: params[:filter]) %>
</div>
<table class="table table-sm table-striped">
  <thead class="thead-light">
    <th scope="col" class="w-auto">Photo</th>
    <th scope="col" class="w-50">Person</th>
    <th scope="col" class="w-auto">Assignments</th>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <%= render partial: "person_as_row", locals:{person: person} %>
    <% end %>
  </tbody>
</table>

app/views/people/new.html.erb
<h1>New Person</h1>
<h3>
	For OPEN Position in <%= @job_status.group.name_jp %>, title: <%= @job_status.job_title_jp %>
</h3>
<div id="person">
	<%= render 'form', person: @person, job_status: @job_status %>
</div>

app/views/people/new.js.erb
document.getElementById('object-content').innerHTML = "<%= j(render partial: 'form', locals: {person: @person}) %>";

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>
<div id='object-content'>
  <%= render @person %>
</div>
<hr>
<%= render "associations", person: @person %>

app/views/people/show.js.erb
document.getElementById('object-content').innerHTML = "<%= j(render @person) %>";
document.getElementById('notice').innerHTML = "<%= j notice %>";