config/routes.rb
Rails.application.routes.draw do
  resources :cost_centers
  resources :rafs
  resources :enrollments
  resources :training_categories
  resources :training_programs
  resources :gradings
  resources :grades do
    member do
      put 'up'
      put 'down'
    end
  end
  resources :groups do
    member do
      put 'up'
      put 'down'
    end
  end
  resources :job_statuses do
    member do
      put 'remove_person'
    end
  end
  resources :people
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  patch 'date', to: 'date#update'

  root to: 'groups#index'
end

app/models/group.rb
# frozen_string_literal: true

# Represents a group within an organization.
# Typically, it will define a set of JobStatuses for
# the same job function. This makes it easier to understand
# open positions. Hence it will often be smaller than an
# organizational group.
class Group < ApplicationRecord
  HIRED_BY_GROUP_NAME = "Japan AGC Biologics Related"
  DID_NOT_JOIN_GROUP_NAME = "Did not join"

  acts_as_nested_set counter_cache: :children_count
  has_many :job_statuses, dependent: :restrict_with_error
  has_many :people, through: :job_statuses

  has_many :current_leader_job_statuses, -> { leaders.current }, class_name: "JobStatus"
  has_many :current_leaders, through: :current_leader_job_statuses, source: :person

  belongs_to  :cost_center, optional: true

  def self.recursive_loop(nodes, &block)
    raise ArgumentError, 'Missing block' unless block_given?

    nodes.each do |node|
      block.call(node)
      node.children.each do |child|
        recursive_loop([child], &block)
      end
    end
  end

  # This is a group to put people who made it half-way through the hiring process,
  # had a Person object assigned (because the probability of joining was deemed high),
  # but eventually did not join.
  def self.not_joined_group
    Group.default_scoped.find_or_create_by!(name_jp: DID_NOT_JOIN_GROUP_NAME) do |group|
      group.notes = "Progressed in hiring but did not join"
    end
  end

  # Groups that contain people who are currently hired
  def self.hired_groups
    Group.find_by!(name_jp: HIRED_BY_GROUP_NAME).self_and_descendants
  end

  # Sort job_statuses by leader status and the associated person's grade and birth_date
  def job_statuses_sorted_by_grade_at(date)
    non_placeholder_js = job_statuses.at(date)
                                     .includes(:person).joins(person: { gradings: :grade })
                                     .where('gradings.started_at <= ? AND ? <= gradings.ended_at',
                                            Time.zone.today, Time.zone.today)
                                     .order(group_leader: :desc, 'grades.position' => :asc, 'people.birth_date' => :asc)

    non_placeholder_non_graded_js = job_statuses.at(date)
                                     .includes(:person).left_outer_joins(person: :gradings)
                                     .where('gradings.id IS NULL')
                                     .order(placeholder: :asc, group_leader: :desc, 'people.birth_date' => :asc)

    # placeholder_js = job_statuses.at(date)
    #                              .includes(:person).where(placeholder: true)

    non_placeholder_js + non_placeholder_non_graded_js
  end

  # Counts the super_grades for all people belonging to this
  # group (does not include descending groups).
  # Returns something like {'Haken' => 2, 'S' => 5, 'E' => 1, 'J' => 1}
  def count_people_by_super_grade_at(date)
    Grade.head_count_grouped_by_grades_for_groups_at_date([self], date)
  end

  # Counts the super_grades for all people belonging to this
  # group and all descending groups.
  # Returns something like {'Haken' => 2, 'S' => 5, 'E' => 1, 'J' => 1}
  def self_and_descendents_count_people_by_super_grade_at(date)
    Grade.head_count_grouped_by_grades_for_groups_at_date(self_and_descendants, date)
  end

  # Cost_center of the closest ancestor with a cost_center_id specified
  def derived_cost_center
    self_and_ancestors.where("cost_center_id IS NOT NULL").last&.cost_center
  end

end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :up, :down]

  # GET /groups
  # GET /groups.json
  def index
    @root_groups = Group.roots
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    respond_to do |format|
      if @group.destroy
        format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.js { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def up
    @group.move_left
    respond_to do |format|
      format.html { redirect_to params[:redirect_to] || groups_url, notice: 'Moved up.' }
      format.json { head :no_content }
    end
  end

  def down
    @group.move_right
    respond_to do |format|
      format.html { redirect_to params[:redirect_to] || groups_url, notice: 'Moved down.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:parent_id, :name_jp, :name_en, :notes, :cost_center_id)
  end
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

# GroupsHelper
module GroupsHelper
  def groups_for_select
    nested_set_options Group do |i|
      "#{'  ' * i.level}|-#{i.name_jp}"
    end
  end

  def russian_doll_tree(group, date, &block)
    result = "<div class=\"tree tree-depth-#{group.depth}\">".html_safe # rubocop:disable Rails/OutputSafety
    result += capture(group, date, &block)
    group.children.each do |child|
      result += russian_doll_tree(child, date, &block)
    end
    result += '</div>'.html_safe
    result
  end
end

app/views/groups/_counts.html.erb
<span class="small">
  Ha:<%= hcg['Haken'] %>/
  Co:<%= hcg['Contract'] %>/
  S:<%= hcg['S'] %>/
  C:<%= hcg['C'] %>/
  E:<%= hcg['E'] %>/
  J:<%= hcg['J'] %>
  Total: <%= hcg['Haken'] + hcg['S'] + hcg['C'] + hcg['E'] + hcg['J']%>,
  <% if hcg['not-Graded'] > 0 %>
    <span style="color: orange">not-Graded: <%= hcg['not-Graded'] %></span>,
  <% end %>
  Open: <%= hcg['Open'] %>
</span>

app/views/groups/_form.html.erb
<%= bs_details_modal size: "none" do %>
  <%= form_with(model: group, local: true) do |form| %>
    <%= bs_modal_header title: "Edit Group" %>
    <div class="modal-body" id="details-modal-body">
      <%= error_messages_box group %>

      <div class="row">
        <div class="col">
          <%= bs_text_field form, :name_jp %>
        </div>
        <div class="col">
          <%= bs_text_field form, :name_en %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= bs_select form, :parent_id, "Parent Group", groups_for_select,
                        {include_blank: true}, {class: "form-control"} %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= bs_select form, :cost_center_id, "Cost Center", CostCenter.all.collect{|cc| ["#{cc.number}-#{cc.description}", cc.id]},
                        {include_blank: true}, {class: "form-control"} %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= bs_text_area form, :notes %>
        </div>
      </div>
    </div>

    <div class="modal-footer">
      <% if group.persisted? %>
        <%= link_to 'Destroy', group, method: :delete, data: { confirm: 'DESTROY GROUP: Are you sure?' }, remote: true, class: "btn btn-danger mr-5" %>
      <% end %>
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/groups/_org_chart_table.html.erb
<% root_groups.each do |root_group| %>
  <%= russian_doll_tree(root_group, date) do |group, date| %>
    <div class="branch-header">
      <div style="float:right;font-size: 9px">
        <%= link_to 'Up', up_group_path(group, redirect_to: groups_path), method: :put %> |
        <%= link_to 'Down', down_group_path(group, redirect_to: groups_path), method: :put %>
      </div>
      <%= link_to group.name_jp, group %> <%= group.name_en %>
      <span style="font-size: 11px;"><%= (dcc = group.derived_cost_center) && "#{dcc.number} - #{dcc.description}" %></span>
      <%= render partial: "groups/counts", locals: {hcg: group.self_and_descendents_count_people_by_super_grade_at(date)} %>
    </div>
    <% unless (job_statuses = group.job_statuses_sorted_by_grade_at(date)).size == 0 %>
      <div class="team-block">
        <%= render partial: "job_statuses/person_with_face", collection: job_statuses, as: :job_status,
                          locals:  {date: date} %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/groups/_profile.html.erb
<p id="notice"><%= notice %></p>

<% content_for :controls do %>
  <%= render :partial => "date/button" %>
  <%= link_to 'Edit', edit_group_path(group), remote: true,
                                              data: {toggle: "modal", target: "#detailsModal"},
                                              class: "btn btn-primary" %>
<% end %>

<h1><%= group.name_jp %> <%= group.name_en %></h1>

<p>
  <%= ([link_to("Top", groups_path)] + group.self_and_ancestors.map{ |g| link_to g.name_jp, g }).join(' > ').html_safe %>
</p>

<p>
  <strong>Global Code:</strong> <%= (dcc = group.derived_cost_center) && "#{dcc.number} - #{dcc.description}" %>
</p>

<p>
  <strong>Notes:</strong> (<%= markdown_syntax_link %>)
  <%= markdown_render group.notes %>
</p>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %> | 
<%= link_to 'Destroy', @group, method: :delete, data: { confirm: 'DESTROY GROUP: Are you sure?' } %><

app/views/groups/edit.js.erb
<%= js_insert_content_into_id id: 'detailsModal',
                         content: (render partial: 'form', locals: {group: @group}),
                         textareas_to_adjust: ['group_notes'] %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<% content_for :controls do %>
  <%= render :partial => "date/button" %>
  <%= link_to "New Group", new_group_path, remote: true,
                                           data: {toggle: "modal", target: "#detailsModal"},
                                           class: "btn btn-primary" %>
<% end %>

<h1 class="clearfix">Org Chart for <%= display_for_date.to_s %></h1>

<%= render :partial => "org_chart_table", :locals => {:root_groups => @root_groups, :date => display_for_date} %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/new.js.erb
<%= js_insert_content_into_id id: 'detailsModal',
                         content: (render partial: 'form', locals: {group: @group}),
                         textareas_to_adjust: ['group_notes'] %>

app/views/groups/show.html.erb
<div id="object-content">
  <%= render 'profile', group: @group %>
</div>

<hr>

<h3>Org Chart <%= display_for_date.to_s %></h3>
<%= render :partial => "org_chart_table", :locals => {root_groups: [@group], date: display_for_date} %>

<h3>Job Statuses (include historic)</h3>
Total: <%= @group.job_statuses.size %> people

<%= link_to "New Job Status", new_job_status_url(job_status:{group_id: @group.id}) %>
<table class="table table-sm">
  <thead class="thead-light">
    <th scope="col">Term</th>
    <th scope="col">Person</th>
    <th scope="col">Assigned to Group</th>
    <th scope="col">Title</th>
    <th scope="col">Reports to</th>
  </thead>

  <tbody>
    <%= render @group.job_statuses.order(started_at: :desc) %>
  </tbody>
</table>

<div>
  <h3>Email Addresses</h3>
  <h5>Current Direct</h5>
  <p class="user-select-all">
    <%= @group.job_statuses.current.map{|js| js.placeholder ? nil : js.person}.map{|p| p ? p.email : nil}.filter{|email| !email.blank?}.join('; ') %>
  </p>

  <h5>Current Direct + Descendant</h5>
  <p class="user-select-all">
    <%= JobStatus.current.where(group_id: @group.descendants.map{|g| g.id} + [@group.id]).map{|js| js.placeholder ? nil : js.person}.map{|p| p ? p.email : nil}.filter{|email| !email.blank?}.join('; ') %>
  </p>
</div>