config/routes.rb
Rails.application.routes.draw do
  resources :cost_centers
  resources :rafs
  resources :enrollments
  resources :training_categories
  resources :training_programs
  resources :gradings
  resources :grades do
    member do
      put 'up'
      put 'down'
    end
  end
  resources :groups do
    member do
      put 'up'
      put 'down'
    end
  end
  resources :job_statuses do
    member do
      put 'remove_person'
    end
  end
  resources :people
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  patch 'date', to: 'date#update'

  root to: 'groups#index'
end

app/controllers/job_statuses_controller.rb
# frozen_string_literal: true

class JobStatusesController < ApplicationController
  before_action :set_job_status, only: [:show, :edit, :update, :destroy, :remove_person]
  before_action :set_group, only: [:new]
  before_action :set_person, only: [:new]

  # GET /job_statuses
  # GET /job_statuses.json
  def index
    if params[:filter] == 'placeholders'
      @job_statuses = JobStatus.placeholders.order(started_at: :desc).all
    else
      @job_statuses = JobStatus.real.order(started_at: :desc).all
    end
  end

  # GET /job_statuses/1
  # GET /job_statuses/1.json
  def show
  end

  # GET /job_statuses/new
  def new
    @job_status = JobStatus.new
    @job_status.group = @group
    @job_status.person = @person
  end

  # GET /job_statuses/1/edit
  def edit
  end

  # POST /job_statuses
  # POST /job_statuses.json
  def create
    @job_status = JobStatus.new(job_status_params)

    respond_to do |format|
      if @job_status.save
        format.html { redirect_to @job_status, notice: 'Job status was successfully created.' }
        # format.js { redirect_to @job_status, notice: 'Job status was successfully created.' }
        format.js  { render inline: "location.reload()", notice: 'Assignment was successfully created.' }
        format.json { render :show, status: :created, location: @job_status }
      else
        format.html { render :new }
        format.js   { render :new }
        format.json { render json: @job_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_statuses/1
  # PATCH/PUT /job_statuses/1.json
  def update
    respond_to do |format|
      if @job_status.update(job_status_params)
        format.html { redirect_to @job_status, notice: 'Job status was successfully updated.' }
        format.js   { render inline: "location.reload()", notice: 'Assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_status }
      else
        format.html { render :edit }
        format.js   { render :edit }
        format.json { render json: @job_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # This will remove the Person from the JobStatus association.
  # The Person will remain intact.
  def remove_person
    respond_to do |format|
      if @job_status.remove_person_and_assign_to_not_joined
        format.html { redirect_to @job_status, notice: 'Person was removed from the Job Status.' }
        format.js   { render inline: "location.reload()", notice: 'Person was removed from the Job Status.' }
        format.json { render :show, status: :ok, location: @job_status }
      else
        format.html { render :edit }
        format.js   { render :edit }
        format.json { render json: @job_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_statuses/1
  # DELETE /job_statuses/1.json
  def destroy
    @job_status.destroy
    respond_to do |format|
      format.html { redirect_to job_statuses_url, notice: 'Job status was successfully destroyed.' }
      format.js   { render inline: "location.reload()", notice: 'Assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_job_status
    @job_status = JobStatus.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def job_status_params
    params.require(:job_status).permit(:person_id, :group_id, :grade_id, :raf_id,
                                       :started_at, :job_title_jp, :job_title_en, :reports_to_id,
                                       :group_leader, :notes, :placeholder)
  end

  def set_group
    @group = params[:job_status][:group_id] ? Group.find(params[:job_status][:group_id]) : nil
  end

  def set_person
    @person = params[:job_status][:person_id] ? Person.find(params[:job_status][:person_id]) : nil
  end
end

app/helpers/job_statuses_helper.rb
# frozen_string_literal: true

# JobStatusesHelper
module JobStatusesHelper
  def link_to_job_status(job_status)
    if (person = job_status.person)
      class_string = person.joined? ? '' : 'yet_to_join'
      tag.span link_to("#{person.name_jp}-#{job_status.group.name_jp}",
                       edit_job_status_path(job_status),
                       {remote: true, data: {toggle:"modal", target:"#detailsModal"}}),
               class: class_string
    else
      tag.span link_to( "OPEN: #{job_status.job_title_jp} #{job_status.group.name_jp}",
                        edit_job_status_path(job_status),
                        {remote: true, data: {toggle:"modal", target:"#detailsModal"}}),
               class: 'yet_to_join'
    end
  end

  def link_to_job_status_in_org_chart(job_status)
    label = "OPEN "
    if job_status.raf
      label += "RAF #{job_status.raf.planning} #{!job_status.raf.approved_date.blank? ? "Approved" : "To be approved"}"
    else
      label += "no RAF"
    end
    link_to label, edit_job_status_path(job_status),
            {remote: true, data: {toggle:"modal", target:"#detailsModal"}}
  end


end

app/views/job_statuses/_form.html.erb
<%= bs_details_modal size: "modal-lg" do %>
  <%= form_with(model: job_status) do |form| %>
    <%= bs_modal_header title: "Edit Job Assignment" + (" for #{link_to job_status.person.name_jp, job_status.person}" if job_status.person).to_s %>
    <div class="modal-body" id="details-modal-body">
      <% if job_status.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(job_status.errors.count, "error") %> prohibited this job_status from being saved:</h2>

          <ul>
            <% job_status.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form.hidden_field :person_id %>

      <div>
        <% bs_scope form_label_width: 6 do %>
          <% if !job_status.person %>
            <div class="text-right">
              <%= link_to "Add new person if high probability", new_person_url(job_status_id: job_status.id) %>
            </div>
          <% end %>
          <%= bs_checkbox form, :placeholder, "Is this an OPEN posiition?" %>
          <%= bs_text_field form, :started_at, "This position will start at (or is OPEN from)" %>
          <div class="text-right"><small><%= link_to("Group: " + job_status.group.name_jp, job_status.group) if job_status.group %></small></div>
          <%= bs_select form, :group_id, "The position is for the following Group", groups_for_select, include_blank: true %>
          <%= bs_checkbox form, :group_leader, "This position is a Group Leader" %>
          <%= bs_text_field form, :job_title_jp, "The title for this Job (JP) is" %>
          <%= bs_text_field form, :job_title_en, "The title for this Job (EN) is" %>
          <%= bs_select form, :reports_to_id, "This position reports to", Person.all.collect{|p| [p.name_jp, p.id]}, include_blank: true %>
          <div class="text-right"><small><%= link_to("RAF: " + job_status.raf.name, job_status.raf) if job_status.raf %></small></div>
          <%= bs_select form, :raf_id, "This position relateds to the following RAF", raf_select_options, include_blank: true %>
          <%= bs_text_area form, :notes %>
        <% end %>
      </div>
    </div>
    <div class="modal-footer">
      <% if job_status.persisted? && job_status.person %>
        <%= link_to "Remove '#{job_status.person.name_jp}' from this Job Assignment", remove_person_job_status_path(job_status), method: :put, data: { confirm: "REMOVE #{job_status.person.name_jp} FROM JOB ASSIGNMENT: Are you sure?" }, remote: true, class: "btn btn-warning" %>
      <% end %>
      <% if job_status.persisted? %>
        <%= link_to 'Destroy', job_status, method: :delete, data: { confirm: 'DESTROY ASSIGNMENT: Are you sure?' }, remote: true, class: "btn btn-danger" %>
      <% end %>
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/job_statuses/_job_status.html.erb
<tr class="<%= job_status.placeholder ? 'open' : '' %> <%= job_status.started_at < today.months_ago(1).beginning_of_month ? 'prior-to-last-month' : '' %>">
  <td><%= link_to job_status.started_at, edit_job_status_path(job_status), {remote: true, data: {toggle:"modal", target:"#detailsModal"}} %>(<%= distance_of_time_in_words_to_now(job_status.started_at) %><%= job_status.started_at - Time.zone.today > 0 ? "後" : "前" %>) - <%= job_status.ended_at > Date.new(2100, 1, 1) ? "" : job_status.ended_at %>
    <%= link_to "RAF↗︎", job_status.raf if job_status.raf %>
  </td>
  <td>
    <%= job_status.person ? link_to(job_status.person.name_jp, job_status.person) : "-" %>
  </td>
  <td><%= job_status.previous&.group&.name_jp %> -> <%= link_to job_status.group.name_jp, job_status.group %></td>
  <td>
  	<%= job_status.group_leader ? "<strong>Group Leader</strong><br>".html_safe : "" %>
  	<%= job_status.job_title_jp %> <%= job_status.job_title_en %></td>
  <td><%= job_status.reports_to_id %></td>
</tr>

app/views/job_statuses/_person_with_face.html.erb
<div class="person-block <%= job_status.group_leader ? "group-leader" : "" %> <%= job_status.placeholder ? 'open' : ''%>">
	<% if job_status.person %>
    <div class="avatar-box">
      <%= image_tag_for_person(job_status.person, class: "avatar") %>
    </div>
    [<%= job_status.person&.grade_at(date)&.name.to_s[0,2]  %>,<%= job_status.person.academic == 'Master' ? 'M' : '' %>]
    <%= link_to job_status.person.name_jp, job_status.person %>
  <% else %>
    <div class="avatar-box">
      <%= image_tag_for_no_photo(class: "avatar") %>
    </div>
    <%= link_to_job_status_in_org_chart(job_status) %>
  <% end %>
  <% if !job_status.job_title_jp.blank? %>
    <span style="font-size: 9px">(<%= job_status.job_title_jp %>)</span>
  <% end %>
</div>

app/views/job_statuses/edit.html.erb
<%= render 'form', job_status: @job_status %>

app/views/job_statuses/edit.js.erb
<%= js_insert_content_into_id id: 'detailsModal',
                         content: render('form', job_status: @job_status) %>

app/views/job_statuses/index.html.erb
<p id="notice"><%= notice %></p>

<% bs_help_modal "Assignments Help" do %>
  <dl>
    <dt>Assignmentとは？</dt>
    <dd>
      AssignmentはPersonとGroupを繋ぐもので、ある人があるグループに属する状態を表します。
    </dd>
    <dt>新規Assignmentの作成</dt>
    <dd>
      AssignmentはからなずGroupもしくはPersonに紐づくため、GroupもしくはPersonの中から作成します。
      例えばあるPersonが新しいGroupに異動する時は、Personの画面から新規Assignmentを作ります。
      また新しく人を雇用するためのOPEN positionを作成する時は、Groupから新規Assignmentを作ります。
    </dd>
    <dt>AssignmentとRAFの関係</dt>
    <dd>
      これは結構難しい
    </dd>
  </dl>
<% end %>

<h1>Assignments</h1>
<% if params[:filter] %>
  Filter: <%= params[:filter] %>
<% end %><br>
<br>
<%= link_to 'all real', job_statuses_path %> |
<%= link_to 'placeholders', job_statuses_path(filter: :placeholders) %>
<br>
Total: <%= @job_statuses.size %> people
<br>

<table id="job_statuses_index" class="table table-sm table-striped">
  <thead class="thead-light">
    <tr>
      <th scope="col">Term</th>
      <th scope="col">Person</th>
      <th scope="col">Assigned to Group</th>
      <th scope="col">Title</th>
      <th scope="col">Reports to</th>
    </tr>
  </thead>

  <tbody>
    <%= render @job_statuses %>
  </tbody>
</table>

app/views/job_statuses/new.html.erb
<h1>New Assignment</h1>
<h2>Person: <%= @job_status.person&.name_jp %></h2>
<h2>Group: <%= @job_status.group.name_jp %></h3>

<%= render 'form', job_status: @job_status %>

<%= link_to 'Back', job_statuses_path %>

app/views/job_statuses/new.js.erb
<%= js_insert_content_into_id id: 'detailsModal',
                         content: render('form', job_status: @job_status) %>

app/views/job_statuses/show.html.erb
<h2>Job Assignment</h2>

<p id="notice"><%= notice %></p>

<p>
  <strong>Person:</strong>
  <% if @job_status.person %>
    <%= link_to @job_status.person.name_jp, person_path(@job_status.person) %>
  <% else %>
    OPEN Position (Person not yet assigned)<br>
    <%= link_to "Add new person if high probability", new_person_url(job_status_id: @job_status.id) %>
  <% end %>
</p>

<p>
  <strong>Group:</strong>
  <%= @job_status.group.name_jp %>
</p>

<p>
  <strong>Started at:</strong>
  <%= @job_status.started_at %>
</p>

<p>
  <strong>Job title jp:</strong>
  <%= @job_status.job_title_jp %>
</p>

<p>
  <strong>Job title en:</strong>
  <%= @job_status.job_title_en %>
</p>

<p>
  <strong>Reports to:</strong>
  <%= @job_status.reports_to_id %>
</p>

<p>
  <strong>RAF:</strong>
  <%= link_to @job_status.raf.name, @job_status.raf if @job_status.raf%>
</p>

<p>
  <strong>Notes:</strong>(<%= markdown_syntax_link %>)
  <%= markdown_render @job_status.notes %>
</p>

<%= link_to 'Edit', edit_job_status_path(@job_status) %> |
<%= link_to 'Back', job_statuses_path %>